/**
 * Public `Channel` API — the community extension point of @dsh/agent-manager
 * (see the package README for the adapter authoring guide).
 *
 * A `Channel` adapter owns one sub-agent **process** and its bidirectional
 * communication with a concrete harness CLI (e.g. Claude Code, codex). This
 * module intentionally has no dependency on process management, the journal
 * or Cordis: adapters receive everything they need through method arguments
 * and the `onEvent` sink, so third parties can implement new harnesses
 * against this module alone.
 *
 * See `packages/agent-manager/README.md` for the adapter authoring guide.
 */
import type { ChannelEvent, JournalEventKind } from '../journal/types.js'

/**
 * Capability flags advertised by an adapter. agent-manager does not act on
 * these flags yet; they exist so callers (and future policy layers) can
 * query what a harness supports before using it.
 */
export interface ChannelCapabilities {
  /** Whether the harness can deliver incremental reply text while a turn runs. */
  streaming: boolean
  /** Whether the channel can keep the child process alive across turns. */
  keepAlive: boolean
  /** Whether an existing harness session can be resumed into a new process. */
  resumeSession: boolean
  /** Whether a running session can be forked. */
  forkSession: boolean
  /** Whether the harness can read back its own conversation history. */
  readHistory: boolean
  /** Whether a system prompt can be injected when the session opens. */
  injectSystemPrompt: boolean
}

/**
 * Arguments for {@link Channel.open}.
 *
 * `agentId` is generated by agent-manager itself and is the authoritative
 * identity used by the journal and every query API. Any harness-native
 * session id (Claude Code `--session-id`, codex `threadId`) is merely an
 * attached field — the two harnesses point in opposite directions (caller
 * supplied vs. server returned), so neither can serve as the unified key.
 */
export interface ChannelOpenOptions {
  /** agent-manager-generated agent id; becomes the journal `agentId`. */
  agentId: string
  /** Working directory of the child process. Defaults to `process.cwd()`. */
  cwd?: string
  /**
   * Optional caller-supplied harness session id (e.g. Claude Code
   * `--session-id`). Adapters that cannot accept one ignore it. When
   * omitted, the adapter generates or receives one from the harness.
   */
  harnessSessionId?: string
  /**
   * Role `system_prompt`, injected through the harness-native mechanism
   * (`--append-system-prompt` for Claude Code, `developerInstructions` for
   * codex) when {@link ChannelCapabilities.injectSystemPrompt} is true.
   */
  systemPrompt?: string
  /** Extra environment variables for the child process. */
  env?: Record<string, string>
  /**
   * Role-requested tool configuration. This is a request, not a grant; the
   * manager currently forwards it pending PolicyResolver.
   */
  tools?: unknown
  /**
   * Role-requested sandbox configuration. This is a request, not a grant; the
   * manager currently forwards it pending PolicyResolver.
   */
  sandbox?: unknown
  /**
   * Third-party tools (MCP servers) this agent gets, by name, already
   * resolved: the role declared them, the project policy allows them, and a
   * launch definition exists. **When present — even as `{}` — the adapter
   * must give the agent exactly these MCP servers and no others**, whatever
   * the harness's own user or project configuration contains; a role may
   * only use tools declared in its definition. `undefined` leaves the
   * harness's own MCP configuration alone (callers that predate this field).
   */
  mcpServers?: Readonly<Record<string, McpServerLaunch>>
  /**
   * Whether to open the agent in a visible window (e.g., tmux session).
   * Default: false (headless background process).
   */
  showWindow?: boolean
  /**
   * Title for the window when showWindow is true.
   */
  windowTitle?: string
  /**
   * Sink for structured, harness-agnostic events observed by the adapter
   * (`message`, `tool_call`, `tool_result`, `command.sent`, `chat.sent`,
   * `chat.replied`, `error`, `agent.exited`, …). The agent-manager feeds
   * these into the journal in real time. Adapters must call it promptly and
   * must never let a blocked `sendChat` delay event delivery.
   */
  onEvent?: (event: ChannelEvent) => void
  /**
   * Called after a structured turn/start request returns a harness turn id.
   * TUI decorators use this to attach only after a remote UI can resume safely.
   */
  onTurnStarted?: (turnId: string) => void
}

/**
 * Handle for one open channel session. `sessionId` is the harness-native
 * identifier; `agentId` remains the authoritative identity.
 */
export interface ChannelSession {
  /** agent-manager-generated agent id (authoritative). */
  agentId: string
  /** Harness identifier of the adapter that opened the session. */
  harness: string
  /**
   * Harness-native session identifier: the Claude Code session id, the codex
   * thread id, etc. Attached metadata only — never the primary key.
   */
  sessionId: string
  /** Optional official remote endpoint that a generic TUI can attach to. */
  endpoint?: string
  /**
   * OS pid of the child process backing this session, when the adapter owns
   * one directly. `AgentManager` advertises this as `childPid` so
   * another process's `FileLiveAgentRegistry.list()` can tell a live orphan
   * (owner died, this pid is still running) from a merely stale entry — it
   * is diagnostic only, nothing here ever signals this pid automatically.
   */
  pid?: number
  /**
   * Window handle (e.g., tmux session name) if the agent was spawned with
   * showWindow=true. Undefined for headless agents.
   */
  windowHandle?: string
  /**
   * Open the agent's window for user interaction.
   * Only available when windowHandle is present.
   */
  openWindow?(): Promise<void>
  /**
   * Close the agent's window without terminating the process.
   * Only available when windowHandle is present.
   */
  closeWindow?(): Promise<void>
}

/**
 * A structured control instruction sent with {@link Channel.sendCommand}.
 * The adapter serializes it per harness; `text` is the human-readable
 * instruction the sub-agent actually sees.
 */
export interface AgentCommand {
  /** Structured command kind, e.g. `'task'` or `'stop'`. */
  kind: string
  /**
   * Structured payload. Kept harness-agnostic here; the journal records it
   * verbatim and the adapter decides how (or whether) to expose it to the
   * sub-agent.
   */
  payload: unknown
  /** Instruction text handed to the sub-agent. */
  text: string
}

/** One tool call observed during a turn (journal `tool_call` summary). */
export interface ChatToolCall {
  /** Harness tool-use id. */
  id: string
  /** Tool name as reported by the harness. */
  name: string
  /** Tool input as reported by the harness. */
  input?: unknown
}

/** Result of one completed {@link Channel.sendChat} round. */
export interface ChatReply {
  /** Full text of the assistant reply for this turn. */
  text: string
  /** Harness-reported model name, when available. */
  model?: string
  /** Wall-clock duration of the round, in milliseconds. */
  durationMs: number
  /** Harness stop reason, when reported (e.g. `end_turn`). */
  stopReason?: string
  /** Tool calls that happened during the turn, in execution order. */
  toolCalls: ChatToolCall[]
  /** Raw harness reply record, for debugging. Opaque by design. */
  raw?: unknown
}

/** Options for {@link Channel.sendChat}. */
export interface SendChatOptions {
  /**
   * Maximum wait for one complete reply, in milliseconds.
   * **Default: 10 minutes (600_000 ms).** Without a timeout a wedged
   * sub-agent would hang the main agent forever.
   */
  timeoutMs?: number
  /**
   * Abort the wait early. Aborting rejects the returned promise with a
   * `ChannelAbortedError`; the adapter should also attempt to cancel the
   * in-flight turn when the harness supports it (codex `turn/interrupt`).
   */
  signal?: AbortSignal
}

/**
 * Default `sendChat` timeout: 10 minutes. Applied whenever neither the
 * call site nor the role's `execution.chatTimeoutMs` overrides it.
 */
/** How to start one MCP server over stdio. */
export interface McpServerLaunch {
  command: string
  args?: string[]
  env?: Record<string, string>
}

export const DEFAULT_SEND_CHAT_TIMEOUT_MS = 600_000

/**
 * Minimum spacing between two `agent.activity` heartbeats a channel records
 * for one session. A harness may report progress every second;
 * the journal only needs enough of it that no working stretch looks like a
 * silence — far below the 5-minute stall threshold, far above the harness's
 * own cadence.
 */
export const DEFAULT_ACTIVITY_HEARTBEAT_MS = 30_000

/**
 * Bidirectional channel to one sub-agent process.
 *
 * ## Contract for adapters
 *
 * - `open` must actually spawn the harness process (no mocks in production).
 * - Role `tools`/`sandbox` requests must only be translated through official
 *   harness options; never weaken the host sandbox implicitly.
 * - Every observable wire event must be forwarded through
 *   {@link ChannelOpenOptions.onEvent} as it happens.
 * - `sendChat` must resolve with one complete reply, honour `timeoutMs`
 *   (default 600_000 ms) and `signal`.
 * - `close` must terminate the child process and wait for it to exit —
 *   leaking orphan processes on dispose is not acceptable.
 * - When the process exits for any reason, the adapter must emit an
 *   `agent.exited` event and reject/fail all in-flight operations.
 *
 * Implementations do not need to be thread-safe: agent-manager serializes
 * `sendCommand`/`sendChat` calls per session.
 */
export interface Channel {
  /** Harness identifier, e.g. `'claude-code'` or `'codex'`. */
  readonly harness: string
  /** Capability flags of this adapter. */
  readonly capabilities: ChannelCapabilities

  /**
   * Spawn the sub-agent process and establish the channel.
   *
   * @param options - agent id, cwd, system prompt, event sink, …
   * @returns the open session handle carrying the harness-native session id.
   */
  open(options: ChannelOpenOptions): Promise<ChannelSession>

  /**
   * Send a structured control instruction.
   *
   * Resolves once the command turn has completed (so callers can rely on
   * process-lifecycle decisions such as `keepAliveAfterTask`), but discards
   * the reply text — use {@link Channel.sendChat} when a reply is needed.
   * The journal records the turn's activity regardless.
   *
   * Meant for control instructions whose outcome nobody judges from the
   * return value. Resolving says the turn ended, not that the
   * work is right: `AgentManager` runs the role's declared `verification`
   * only on `sendChat`, so work to be dispatched and checked goes there.
   *
   * @param session - session returned by {@link Channel.open}.
   * @param command - structured command to dispatch.
   */
  sendCommand(session: ChannelSession, command: AgentCommand): Promise<void>

  /**
   * Send free-form text and wait for exactly one complete reply.
   *
   * Non-streaming by design: partial half-sentences have no
   * decision value for the main agent. Progress during long turns is
   * observable through the journal, which keeps appending while this
   * promise is pending.
   *
   * @param session - session returned by {@link Channel.open}.
   * @param text - message text for the sub-agent.
   * @param options - timeout override (default 600_000 ms) and AbortSignal.
   * @returns the complete reply of this turn.
   */
  sendChat(session: ChannelSession, text: string, options?: SendChatOptions): Promise<ChatReply>

  /**
   * Close the channel and terminate the child process. Idempotent: closing
   * an already-closed session resolves without error. All in-flight
   * operations reject with `ChannelClosedError`.
   *
   * @param session - session returned by {@link Channel.open}.
   */
  close(session: ChannelSession): Promise<void>
}

/** True when `error` is an `AbortError` created by aborting an AbortSignal. */
export function isAbortError(error: unknown): boolean {
  return error instanceof Error
    && (error.name === 'AbortError'
      || ('code' in error && (error as Error & { code?: unknown }).code === 'aborted'))
}

/** Canonical list of harness ids implemented by @dsh/agent-manager itself. */
export const BUILT_IN_HARNESSES = ['claude-code', 'codex'] as const

/** Branded harness id for built-in adapters; community adapters use plain strings. */
export type BuiltInHarness = (typeof BUILT_IN_HARNESSES)[number]

export type { ChannelEvent, JournalEventKind }
